/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://77ut5hljrbbhthdthbdoubhoqe.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xh23oheinze3rhrvrov4rlth5e",
    "aws_cognito_identity_pool_id": "ca-central-1:b4a3be7e-df51-45df-a59e-80de3489d208",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_ba2HbgxtB",
    "aws_user_pools_web_client_id": "2ocmumiagnpa5oll4dsi77pheo",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
